apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-grafana
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - grafana.cardpay.udstecnologia.com.br
    secretName: cert-grafana-prd
  rules:
    - host: grafana.cardpay.udstecnologia.com.br
      http:
        paths:
        - backend:
            serviceName: eks-monitor-grafana
            servicePort: 80
