apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:11.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
            - mountPath: /etc/timezone:/etc/timezone:ro
              name: postgredb
            - mountPath: /etc/localtime:/etc/localtime:ro
              name: 
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim