apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: consul-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: consul.cardpay.udstecnologia.com.br
    http:
      paths:
      - path: /
        backend:
          serviceName: consul-service
          servicePort: http