

apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::563366818355:role/eks-cardpay-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::563366818355:user/vinicius.ribeiro@uds.com.br
      username: vinicius.ribeiro@uds.com.br
      groups:
        - system:masters
    - userarn: arn:aws:iam::563366818355:user/galhardoro@icloud.com
      username: galhardoro@icloud.com
      groups:
        - system:masters
    - userarn: arn:aws:iam::563366818355:user/cardpay-cli
      username: cardpay-cli
      groups:
        - system:masters

